"""Initial migration

Revision ID: d137b4909012
Revises: 
Create Date: 2026-07-01 17:05:10.177192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd137b4909012'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'clinician', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.SmallInteger(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_heart_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('calories_burned >= 0', name='chk_calories'),
    sa.CheckConstraint('duration_min > 0', name='chk_activity_duration'),
    sa.CheckConstraint('intensity BETWEEN 1 AND 5', name='chk_intensity'),
    sa.CheckConstraint('steps >= 0', name='chk_steps'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_date'), 'activity_logs', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('health_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('mood_score', sa.SmallInteger(), nullable=True),
    sa.Column('stress_level', sa.SmallInteger(), nullable=True),
    sa.Column('energy_level', sa.SmallInteger(), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('calories >= 0 AND calories <= 10000', name='chk_calories'),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 10', name='chk_energy_level'),
    sa.CheckConstraint('health_score >= 0.0 AND health_score <= 100.0', name='chk_health_score'),
    sa.CheckConstraint('heart_rate_bpm >= 30 AND heart_rate_bpm <= 250', name='chk_heart_rate'),
    sa.CheckConstraint('mood_score BETWEEN 1 AND 10', name='chk_mood_score'),
    sa.CheckConstraint('sleep_hours >= 0.0 AND sleep_hours <= 24.0', name='chk_sleep_hours'),
    sa.CheckConstraint('steps >= 0 AND steps <= 100000', name='chk_steps'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 10', name='chk_stress_level'),
    sa.CheckConstraint('water_ml >= 0', name='chk_water_ml'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_health_log_user_date')
    )
    op.create_index(op.f('ix_health_logs_log_date'), 'health_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_health_logs_user_id'), 'health_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('reminder', 'insight', 'achievement', 'alert', 'system', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('push', 'email', 'in_app', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'pre_workout', 'post_workout', name='mealtype'), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('total_calories >= 0', name='chk_total_calories'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_log_date'), 'nutrition_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('sleep', 'activity', 'nutrition', 'hydration', 'stress', 'general', name='reccategory'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='recpriority'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0.0 AND 1.0', name='chk_confidence'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_recommendations_generated_at'), 'recommendations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_stages', sa.JSON(), nullable=True),
    sa.Column('interruptions', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('interruptions >= 0', name='chk_interruptions'),
    sa.CheckConstraint('quality_score BETWEEN 1 AND 10', name='chk_sleep_quality'),
    sa.CheckConstraint('wake_time > bedtime', name='chk_wake_after_bed'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_sleep_date'), 'sleep_logs', ['sleep_date'], unique=False)
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'non_binary', 'prefer_not_to_say', name='gendertype'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active', name='activitylevel'), nullable=True),
    sa.Column('health_goals', sa.JSON(), nullable=True),
    sa.Column('medical_conditions', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('nutrition_items',
    sa.Column('nutrition_log_id', sa.Uuid(), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('serving_qty', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('serving_unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('calories >= 0', name='chk_item_calories'),
    sa.CheckConstraint('serving_qty > 0', name='chk_serving_qty'),
    sa.ForeignKeyConstraint(['nutrition_log_id'], ['nutrition_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_items_nutrition_log_id'), 'nutrition_items', ['nutrition_log_id'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_actions_recommendation_id'), 'recommendation_actions', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_actions_recommendation_id'), table_name='recommendation_actions')
    op.drop_table('recommendation_actions')
    op.drop_index(op.f('ix_nutrition_items_nutrition_log_id'), table_name='nutrition_items')
    op.drop_table('nutrition_items')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_sleep_date'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_generated_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_category'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_log_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_health_logs_user_id'), table_name='health_logs')
    op.drop_index(op.f('ix_health_logs_log_date'), table_name='health_logs')
    op.drop_table('health_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_date'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
